### PR TITLE
backup Security database separately ML258

### PR DESCRIPTION
**Pull request by xinjianguo**
Separate the lux-content database and the security database backups

### CODE REVIEW

**Comment by brent-hartwig** [comment]
@xinjianguo, please confirm your intent to backup daily at 11:50 server time and only keep one backup:

```
      "backup-type": "daily",
      "backup-period": 1,
      "backup-start-time": "11:50:00",
      "max-backups": 1,
```

My concern would be we could only ever go back one day.  I did suggest daily in the original ticket.  I could see doing that but keeping a week's worth -or- switching to weekly and keeping three weeks' worth.

As for the time of day, 11:50 is fine.  Just seemed a little random (or the time you last tested).

**Comment by xinjianguo** [comment]
> @xinjianguo, please confirm your intent to backup daily at 11:50 server time and only keep one backup:
> 
> ```
>       "backup-type": "daily",
>       "backup-period": 1,
>       "backup-start-time": "11:50:00",
>       "max-backups": 1,
> ```
> 
> My concern would be we could only ever go back one day. I did suggest daily in the original ticket. I could see doing that but keeping a week's worth -or- switching to weekly and keeping three weeks' worth.
> 
> As for the time of day, 11:50 is fine. Just seemed a little random (or the time you last tested).

yup, that was a leftover from the local testing, needs to be adjusted to be the same time as the daily of lux-content.

**Comment by xinjianguo** [comment]
updated to 05:00:00

**Comment by brent-hartwig** [comment]
@xinjianguo, I hope you don't mind but I made a couple changes:

1. Staggered start time in case there's a reversion and we start including the Security database in lux-content's backup; at which point one of the scheduled jobs would fail.
2. Increased the maximum number of backups primarily in the case that an invalid/corrupt backup is created over the weekend and we do not notice until Monday.

**Pull request merged**
