### PR TITLE
256 fix date sorting

### PR DESCRIPTION
**Pull request by clarkepeterf**

### CODE REVIEW

**Comment by clarkepeterf** [comment]
Thanks @brent-hartwig 

1. Sorry for the short timeframe. Let me know if you want to test more tomorrow
2. Nice
3. The XPaths of the DateStr indexes are referenced in similar queries, which are unused at the moment. This could be refactored if we want to remove the DateStr indexes
4. Brief Testing DEV vs GREEN: Dev initially takes 2.07s, 1162ms, 1129ms, 1201ms, 1300ms. Green takes 1007ms, 1013ms, 1026ms, 1096ms, 1034ms.
  The query was:
    - name=`itemProductionDate`
    - q=`{"OR":[{"memberOf":{"curatedBy":{"id":"https://lux.collections.yale.edu/data/group/d07b9b86-0a1e-4026-aa4c-8ecba8bbd9c9"}}},{"memberOf":{"curatedBy":{"memberOf":{"id":"https://lux.collections.yale.edu/data/group/d07b9b86-0a1e-4026-aa4c-8ecba8bbd9c9"}}}}]}`
    - scope=`item `
    - page=`1`
    - pageLength=`10000`
    - sort=`asc`
5. 😬 - sorry I accidentally overwrote these changes
6. I made some additional changes - require years match the ISO 8601 format (prepended 0s, negative years must have 6 digits), and use the same conversion for years to/from seconds. This makes your example query match. But also requires that you submit in an ISO 8601 compliant format (`'-001982-12-31T12:00:00'`)

**Comment by brent-hartwig** [comment]
I'm good with leaving the dates-as-strings indexes for now.

I don't imagine a 1/5th of a second longer for 10K date facet values will become a problem --at least not at current usage.

I added my edits back in.

Since your last edits to dateUtils, I haven't been able to find a variance.  Script below.  Nice job.

```javascript
import * as du from '/utils/dateUtils'
[
  "-000001-01-01T00:00:00",
  "-000001-12-31T12:00:00",
//   "-000000-01-01T12:34:56", // errors out
  "0000-01-01T00:00:00",
  "0001-01-01T12:34:56",
  "1982-12-31T12:00:00",
  "-001982-12-31T00:00:00",
  "-001982-12-31T23:59:59",
  "-65000000-01-01T00:00:00", // dino
  "-65000000-12-31T23:59:59",
  "-140000000-01-01T00:00:00", // older fossil found in sidewalk
  "-140000000-12-31T23:59:59",
  "100000-01-01T00:00:00",
  "100000-12-31T00:00:00",
].map(dateStr => {
  const seconds = du.convertPartialDateTimeToSeconds(dateStr)
  const result = {
    "_input": dateStr,
    output: du.convertSecondsToDateStr(seconds),
    seconds,
  }
  return result;
})
```

I do see we "support" year zero.  Not sure who is going to call us out on that :)

API usage documentation may need a section on dates, especially if the endpoint consumer is responsible for including a minimum of six digit years when negative.

I was able to test the endpoint a little locally:

1. The values appear to be formatted as expected.
2. The values appear to be sorted correctly (frequency, asc, and desc)
3. I feel like there was something else I confirmed, but on to the questions.

Did you test sort and conversion of years that are outside the -9999:9999 range?

How about a negative year that has seven digits?

Did you test clicking on the facet values and making sure they work?  I took the search criteria from one, generated the query, ran the search and receive zero results.  Perhaps an issue with the date search pattern (#37)?

If you also have the most recent small dataset, this should be the same for you:

```json
{
  "id":"https://lux.collections.yale.edu/api/search-estimate/work?q=%7B%22AND%22%3A%5B%7B%22text%22%3A%22book%22%2C%22_lang%22%3A%22en%22%7D%2C%7B%22AND%22%3A%5B%7B%22createdDate%22%3A%22-001500-01-01T00%3A00%3A00.000Z%22%2C%22_comp%22%3A%22%3E%3D%22%7D%2C%7B%22createdDate%22%3A%22-001500-01-01T00%3A00%3A00.000Z%22%2C%22_comp%22%3A%22%3C%3D%22%7D%5D%7D%5D%7D",
  "type":"OrderedCollection",
  "totalItems":1,
  "value":"-001500-01-01T00:00:00.000Z"
}
```

All facet endpoint param values:

image

Aside: what's the purpose of the facet value id property values being search-estimate calls?

Thank you!

**Comment by clarkepeterf** [comment]
@brent-hartwig Thanks for reviewing again

> I do see we "support" year zero. Not sure who is going to call us out on that :)
 - We are using ISO 8601 dates which take year 0000 to be equivalent to 1 BCE. Whether to display it like that on the frontend is up to the client.

> Did you test sort and conversion of years that are outside the -9999:9999 range

 - Yes, this works, but also since we only convert use years, there is some loss of precision outside of that range. It is actually decided on the frontend to ONLY support [-9999:9999]. Outside of that range will likely use something else (e.g. does this fossil come from the **_cretaceous period_**?) But I left support for just years outside that range in ML in case we want to bring that back.

> How about a negative year that has seven digits?

 - Yep, I have tested things like -65000000 and 65000000 which have 8 digits

> Did you test clicking on the facet values and making sure they work? I took the search criteria from one, generated the query, ran the search and receive zero results. Perhaps an issue with the date search pattern (https://github.com/project-lux/lux-marklogic/issues/37)?

 - I don't get any responses for that search locally, so I can't reproduce.
 - However, these date changes are deployed in DEV, and they get the same facet results as TST/PRD. E.g. [DEV search](https://lux-front-dev.collections.yale.edu/view/results/objects?q=%7B%22AND%22%3A%5B%7B%22text%22%3A%22andy%22%2C%22_lang%22%3A%22en%22%7D%2C%7B%22text%22%3A%22warhol%22%2C%22_lang%22%3A%22en%22%7D%5D%7D&sq=andy+warhol&if=%7B%22AND%22%3A%5B%7B%22producedDate%22%3A%221782%22%2C%22_comp%22%3A%22%3E%3D%22%7D%2C%7B%22producedDate%22%3A%222020%22%2C%22_comp%22%3A%22%3C%3D%22%7D%5D%7D&facetRequest=true&ip=1) matches [TST Search](https://lux-front-tst.collections.yale.edu/view/results/objects?q=%7B%22AND%22%3A%5B%7B%22text%22%3A%22andy%22%2C%22_lang%22%3A%22en%22%7D%2C%7B%22text%22%3A%22warhol%22%2C%22_lang%22%3A%22en%22%7D%5D%7D&sq=andy+warhol&if=%7B%22AND%22%3A%5B%7B%22producedDate%22%3A%221782%22%2C%22_comp%22%3A%22%3E%3D%22%7D%2C%7B%22producedDate%22%3A%222020%22%2C%22_comp%22%3A%22%3C%3D%22%7D%5D%7D&facetRequest=true&ip=1). There are some issues with the frontend's interpretation of negative date facets but I'll be deploying a frontend fix for that shortly.
 - My response for the same local facet request below:
 
```
{
    "@context": "https://linked.art/ns/v1/search.json",
    "id": "https://lux.collections.yale.edu/api/facets/work?q=%7B%22text%22%3A%22book%22%2C%22_lang%22%3A%22en%22%7D&name=workCreationDate&page=1&pageLength=10000",
    "type": "OrderedCollectionPage",
    "partOf": {
        "type": "OrderedCollection",
        "totalItems": 0
    },
    "orderedItems": []
}
```

> Aside: what's the purpose of the facet value id property values being search-estimate calls?

- It's an Activity Streams thing. Each entry in the `orderedItems` of a facet request is an OrderedCollection. (An OrderedCollection contains a collection of items, in our case, a collection of items that match a search).  The **search-estimates** endpoint returns an OrderedCollection. If you look at the response from `search-estimates`, if has a `first` / `last` property with a link to the **search** endpoint which returns an OrderedCollectionPage (a specific page of items within the OrderedCollection)

**Comment by brent-hartwig** [comment]
Thanks for all the responses and diligence 💥

**Comment by clarkepeterf** [comment]
@brent-hartwig no problem, thank you for reviewing 😁

Ok to merge?

**Comment by brent-hartwig** [comment]
Yes sir

**Pull request merged**
